version: '2'

services:

  # Stock Analysis Engine
  # Automation Dataset Collector
  sa-dataset-collection:
    container_name: "sa-dataset-collection-${USER}"
    hostname: "sa-dataset-collection-1-${USER}"
    image: jayjohnson/stock-analysis-engine:latest
    tty: true
    env_file:
      - ./envs/.env
    entrypoint: "/bin/sh -c 'cd /opt/sa && 
                 . /opt/venv/bin/activate &&
                 /opt/sa/tools/start-dataset-collection.sh'"
