version: '2'

services:

  # Redis
  redis:
    container_name: "redis-${USER}"
    hostname: "redis-${USER}"
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"

  # Minio
  minio:
    container_name: "minio-${USER}"
    hostname: "minio-${USER}"
    image: minio/minio:latest
    env_file:
      - ./envs/local.env
    ports:
      - "9000:9000"
    volumes:
      - /data/minio/data:/data
    command: "server /data"

  # Stock Analysis Engine
  sa-workers:
    container_name: "sa-workers-${USER}"
    hostname: "sa-workers-${USER}"
    image: jayjohnson/stock-analysis-engine:latest
    tty: true
    env_file:
      - ./envs/local.env
    depends_on:
      - redis
      - minio
    entrypoint: "/bin/sh -c 'cd /opt/sa && 
                 /opt/sa/start-workers.sh'"

  # Jupyter notebooks, converted noteooks as presentation html slides, and tensorboard
  sa-jupyter:
    container_name: "sa-jupyter-${USER}"
    hostname: "sa-jupyter-${USER}"
    image: jayjohnson/stock-analysis-jupyter:latest
    tty: true
    env_file:
      - ./envs/local.env
    depends_on:
      - redis
      - minio
    ports:
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
      - "6006:6006"
    entrypoint: "/opt/sa/docker/jupyter/start-container.sh"
