version: '2'

services:

  # Minio
  minio:
    container_name: "minio"
    hostname: minio
    image: minio/minio:latest
    network_mode: "host"
    environment:
      - MINIO_ACCESS_KEY="trexaccesskey"
      - MINIO_SECRET_KEY="trex123321"
    ports:
      - "9000:9000"
    volumes:
      - /data/minio/data:/data
    command: "server /data"
