version: '2'

services:

  # Redis
  redis:
    container_name: "redis-${USER}"
    hostname: "redis-${USER}"
    image: redis:4.0.9-alpine
    ports:
      - "${REDIS_PORT}:6379"

  # Minio
  minio:
    container_name: "minio-${USER}"
    hostname: "minio-${USER}"
    image: minio/minio:latest
    env_file:
      - ./envs/.env
    ports:
      - "${MINIO_PORT}:9000"
    volumes:
      - /data/minio/data:/data
    command: "server /data"

  # Stock Analysis Engine
  sa-workers:
    container_name: "sa-workers-${USER}"
    hostname: "sa-workers-${USER}"
    image: jayjohnson/stock-analysis-engine:latest
    tty: true
    env_file:
      - ./envs/.env
    depends_on:
      - redis
      - minio
    entrypoint: "/bin/sh -c 'cd /opt/sa && 
                 /opt/sa/start-workers.sh'"

  # Jupyter notebooks, converted noteooks as presentation html slides, and tensorboard
  sa-jupyter:
    container_name: "sa-jupyter-${USER}"
    hostname: "sa-jupyter-${USER}"
    image: jayjohnson/stock-analysis-jupyter:latest
    tty: true
    env_file:
      - ./envs/.env
    depends_on:
      - redis
      - minio
    volumes:
      # please run this from the repo
      # base directory
      - /data/sa/notebooks:/opt/notebooks
    ports:
      - "${JUPYTER_PORT_1}:8888"
      - "${JUPYTER_PORT_2}:8889"
      - "${JUPYTER_PORT_3}:8890"
      - "${JUPYTER_PORT_4}:6006"
    entrypoint: "/opt/sa/docker/jupyter/start-container.sh"
