version: '2'

services:

  # Stock Analysis Engine
  sa-workers:
    container_name: "sa-workers"
    hostname: sa-workers
    image: jayjohnson/stock-analysis-engine:latest
    network_mode: "host"
    entrypoint: "/bin/sh -c 'cd /opt/sa && 
                 /opt/sa/start-workers.sh'"
