apiVersion: v1
kind: Secret
metadata:
  name: ae.k8.minio.s3
type: Opaque
data:
  # echo -n "${AWS_ACCESS_KEY_ID}" | base64
  # trexaccesskey
  aws_access_key_id: dHJleGFjY2Vzc2tleQ==
  # echo -n "${AWS_SECRET_ACCESS_KEY}" | base64
  # trex123321
  aws_secret_access_key: dHJleDEyMzMyMQ==
  # echo -n "minio-service:9000" | base64
  s3_address: bWluaW8tc2VydmljZTo5MDAw
---
apiVersion: v1
kind: Secret
metadata:
  name: ae.k8.aws.s3
type: Opaque
data:
  # echo -n "${AWS_ACCESS_KEY_ID}" | base64
  aws_access_key_id: SET_YOUR_ENCODED_AWS_ACCESS_KEY_ID
  # echo -n "${AWS_SECRET_ACCESS_KEY}" | base64
  aws_secret_access_key: SET_YOUR_ENCODED_AWS_SECRET_ACCESS_KEY
  # echo -n "s3.us-east-1.amazonaws.com" | base64
  s3_address: czMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20=
